---
title: "Projects"
---

**PhD Project - Assessing Structural Differences among Genetically Improved Coastal Douglas‐fir using High Density Airborne Laser Scanning**

1.  Du Toit, F., Coops, N. C., Ratcliffe, B., El‐kassaby, Y. A., & Lucieer, A. (2023). Modelling internal tree attributes for breeding applications in Douglas‐fir progeny trials using RPAS‐ALS. Science of Remote Sensing, 7(November 2022), 100072. <https://doi.org/10.1016/j.srs.2022.100072>
2.  Du Toit, F., Coops, N. C., Ratcliffe, B., & El‐Kassaby, Y. A. (2022). Generating Douglas‐fir Breeding Value Estimates Using Airborne Laser Scanning Derived Height and Crown Metrics. Frontiers in Plant Science, 13(July). <https://doi.org/10.3389/fpls.2022.893017>
3.  Du Toit, F., Coops, N. C., Goodbody, T. R. H., Stoehr, M., & El‐Kassaby, Y. A. (2021). Deriving internal crown geometric features of Douglas‐ fir from airborne laser scanning in a realized‐gain trial. Forestry: An International Journal of Forest Research, 94(3), 442–454. <https://doi.org/10.1093/forestry/cpaa046>
4.  Du Toit, F., Coops, N. C., Tompalski, P., Goodbody, T. R. H., El‐Kassaby, Y. A., Stoehr, M., Turner, D., & Lucieer, A. (2020). Characterizing variations in growth characteristics between Douglas‐fir with different genetic gain levels using airborne laser scanning. Trees ‐ Structure and Function, 34(3), 649–664. <https://doi.org/10.1007/s00468-019-01946-y>

**Postdoc - Carbon Sequestration Optimization in Canadian Forests**

1.  Du Toit, F., Coops, N. C., Mulverhill, C., & Toomey, A., (2024). Assessing the impact of afforestation as a natural climate solution in the Canadian boreal. *Environmental Research: Ecology*, *3*(3), 035004. <https://doi.org/10.1088/2752-664X/ad67e6>
2.  3-PG help guide: <https://francoisdt14.github.io/3PG-Help/>
